### ISSUE TITLE
大佬，我这个换成manage.py里面的 code_testing了，还是不行，还是那个bug

### ISSUE THREAD

**Issue by siran575** [yutu-75/jianyubiaoxun#5]
![image](https://user-images.githubusercontent.com/73805034/124438185-75796180-ddaa-11eb-8ca1-8a23bf121604.png)

**Comment by yutu-75** [comment]
manage 里面我是用的requests 没有用 sessions 你没改对   
我刚刚试了 能跑通的

**Comment by siran575** [comment]
![image](https://user-images.githubusercontent.com/73805034/124444157-e754a980-ddb0-11eb-8da5-e665ba006953.png)
这样manage才会有session的，程序在pycharm我也能跑通，但是打包之后就会报错。在想是不是打包环境出问题了，程序是没问题的呢

**Comment by yutu-75** [comment]
manage.py 不会报错的话&nbsp; &nbsp;打包也不会报错的 除非打包失败



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月5日(星期一) 下午4:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yutu-75/jianyubiaoxun] 大佬，我这个换成manage.py里面的 code_testing了，还是不行，还是那个bug (#5)





 

 这样manage才会有session的，程序在pycharm我也能跑通，但是打包之后就会报错。在想是不是打包环境出问题了，程序是没问题的呢

**Comment by siran575** [comment]
![image](https://user-images.githubusercontent.com/73805034/124446995-8b3f5480-ddb3-11eb-85c4-5e1d6867c366.png)
![image](https://user-images.githubusercontent.com/73805034/124447017-909c9f00-ddb3-11eb-9179-44eccd4e0442.png)
![image](https://user-images.githubusercontent.com/73805034/124447041-95f9e980-ddb3-11eb-8d11-91619e706d0d.png)
![image](https://user-images.githubusercontent.com/73805034/124447066-9abe9d80-ddb3-11eb-85c9-5b2c2804796a.

**Comment by siran575** [comment]
![image](https://user-images.githubusercontent.com/73805034/124447952-7ca56d00-ddb4-11eb-8583-b2a21319f4dc.png)
![image](https://user-images.githubusercontent.com/73805034/124447961-7fa05d80-ddb4-11eb-8575-c3d0de346cb7.png)
![image](https://user-images.githubusercontent.com/73805034/124447969-8202b780-ddb4-11eb-85ca-a9fcdd1a4ff0.png)
![image](https://user-images.githubusercontent.com/73805034/124447985-85963e80-ddb4-11eb-8acc-d62a77112e91.png)
![image](https://user-images.githubusercontent.com/73805034/124448029-921a9700-ddb4-11eb-9bb2-ffbb32d3a740.png)
基本步骤这这里了，pycharm运行没问题，也打包成功了，但是打包文件运行有问题，搞了很久，找不到bug,网上也搜过很多。拜托大佬能再帮忙看看哈，万分感谢。。。

**Comment by yutu-75** [comment]
加q吧&nbsp; 我都不知道遇到什么问题 39017764



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月5日(星期一) 下午5:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yutu-75/jianyubiaoxun] 大佬，我这个换成manage.py里面的 code_testing了，还是不行，还是那个bug (#5)





 

 
 
 
 
 基本步骤这这里了，pycharm运行没问题，也打包成功了，但是打包文件运行有问题，搞了很久，找不到bug,网上也搜过很多。拜托大佬能再帮忙看看哈，万分感谢。。。

**Comment by siran575** [comment]
大佬，你那里有隐私设置，加不了。我的qq302164734，可以的话，加一下我。

**Comment by yutu-75** [comment]
加了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月5日(星期一) 下午5:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yutu-75/jianyubiaoxun] 大佬，我这个换成manage.py里面的 code_testing了，还是不行，还是那个bug (#5)





 
大佬，你那里有隐私设置，加不了。我的qq302164734，可以的话，加一下我。
